# Generated by Django 6.1 on 2026-08-31 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('initials', models.CharField(blank=True, max_length=8)),
                ('color', models.CharField(default='bg-violet-100 text-violet-600', max_length=80)),
                ('avatar_seed', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(default='Meetings', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('connected', models.BooleanField(default=False)),
                ('last_sync', models.CharField(blank=True, max_length=80)),
                ('icon', models.CharField(default='zap', max_length=40)),
                ('catalog', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Sarah', max_length=80)),
                ('last_name', models.CharField(default='Chen', max_length=80)),
                ('email', models.EmailField(default='sarah@company.com', max_length=254)),
                ('role', models.CharField(default='Project Manager', max_length=120)),
                ('auto_extract', models.BooleanField(default=True)),
                ('sensitivity', models.PositiveIntegerField(default=75)),
                ('language', models.CharField(default='English (US)', max_length=40)),
                ('timezone', models.CharField(default='Pacific Time (PT) - UTC-8', max_length=80)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_push', models.BooleanField(default=True)),
                ('notify_slack', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='Product', max_length=80)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed')], default='completed', max_length=40)),
                ('summary', models.TextField(blank=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('attendees', models.ManyToManyField(blank=True, related_name='meetings', to='api.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('source', models.CharField(default='Zoom Sync', max_length=80)),
                ('source_kind', models.CharField(default='zoom', max_length=40)),
                ('deadline', models.CharField(blank=True, max_length=80)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Not Started', max_length=40)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('speaker', models.CharField(blank=True, max_length=120)),
                ('speaker_seed', models.CharField(blank=True, max_length=80)),
                ('time', models.CharField(blank=True, max_length=16)),
                ('confidence', models.PositiveIntegerField(default=90)),
                ('action_label', models.CharField(blank=True, max_length=80)),
                ('badge', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.contact')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='api.meeting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.task')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=16)),
                ('speaker', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('is_action', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='api.meeting')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
